language: cpp

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install python-dev libsnappy-dev libtool yasm libchromaprint-dev portaudio19-dev libboost-dev
  - sudo apt-get install libavformat-dev

script:
  - python setup.py build
  - sudo python setup.py install
  - python -c "import musicplayer as mp; p = mp.createPlayer()"
